HealthBlog/Controllers/ContentController.cs
using HealthBlog.Bussiness.Concrete;
using HealthBlog.DataAccess.Concrete.EntityFramework;
using HealthBlog.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using System.IO;

namespace HealthBlog.Controllers
{
    public class ContentController : Controller
    {
        ContentManager contentManager = new ContentManager(new EfContentDal());
        CategoryManager _categoryManager = new CategoryManager(new EfCategoryDal());
        WriterManager _writeryManager = new WriterManager(new EfWriterDal());


        public ActionResult Index(/*int sayfa=1*/)
        {
            //var list = contentManager.GetContentList().ToPagedList(sayfa,7);
            var list = contentManager.GetContentList();
            return View(list);
        }

        public ActionResult ContentListByCategoryId(int id)
        {
            var liste = contentManager.ContentListByCategoryId(id);
            var content = liste.FirstOrDefault();
            ViewBag.category = content.Category.CategoryName;
            return View(liste);
        }


        [HttpGet]
        public ActionResult EditContent(int id)
        {
            var content = contentManager.GetByID(id);

            SelectList();

            return View(content);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditContent(Content content)
        {
            if (Request.Files.Count > 0)
            {
                string filename = Path.GetFileName(Request.Files["ContentImage"].FileName);
                string _filename = DateTime.Now.ToString("yymmssfff") + filename;
                string path = "~/FrontendFiles/ContentImages/" + _filename;
                Request.Files["ContentImage"].SaveAs(Server.MapPath(path));
                content.ContentImage = _filename;
            }

            contentManager.ContentUpdate(content);
            return RedirectToAction("AdminContents"); // hata veriyor sadece yönlendiremiyorum sayfaya
        }


        [HttpGet]
        public ActionResult AddContent()
        {
            SelectList();
            return View();
        }

        public ActionResult ContentListByWriter(int id)
        {
            var list = contentManager.ContentListByWriterId(id);
            var writer = list.FirstOrDefault();
            ViewBag.writer = writer.Writer.WriterTitle + " " + writer.Writer.WriterName + " " + writer.Writer.WriterSurname; 
            return View(list);
        }


        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddContent(Content content)
        {
            if (Request.Files.Count > 0)
            {
                string filename = Path.GetFileName(Request.Files["ContentImage"].FileName);
                string _filename = DateTime.Now.ToString("yymmssfff") + filename;
                string path = "~/FrontendFiles/ContentImages/" + _filename;
                Request.Files["ContentImage"].SaveAs(Server.MapPath(path));
                content.ContentImage = _filename;
            }

            content.ContentDate = DateTime.Now;
            contentManager.ContentAdd(content);
            return RedirectToAction("AdminContents");
        }

        public ActionResult DeleteContent(int id)
        {
            var entity = contentManager.GetByID(id);
            contentManager.ContentDelete(entity);
            //return RedirectToAction("Index","Content");   // herşey doğru siliyor ama sayfaya yönlendirme de sorun var 
            return RedirectToAction("AdminContents");   // herşey doğru siliyor ama sayfaya yönlendirme de sorun var 
        }

        public ActionResult AdminContents()
        {
            var list = contentManager.GetContentList();
            return View(list);
        }


        private void SelectList()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "True", Value = "True", Selected = true });
            items.Add(new SelectListItem { Text = "False", Value = "False" });

            ViewBag.StatusType = items;

            List<SelectListItem> valueCategory = (from x in _categoryManager.GetCategoryList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryId.ToString()
                                                  }).ToList();

            ViewBag.valueCategory = valueCategory;

            List<SelectListItem> valueWriter = (from x in _writeryManager.GetWriterList()
                                                select new SelectListItem
                                                {
                                                    Text = x.WriterName + " " + x.WriterSurname,
                                                    Value = x.WriterId.ToString()
                                                }).ToList();

            ViewBag.valueWriter = valueWriter;
        }

        public ActionResult ContentReport()
        {
            var contentValues = contentManager.GetContentList();
            return View(contentValues);

        }


    }
}

HealthBlog/Views/Content/AddContent.cshtml
@model HealthBlog.Entities.Concrete.Content

@{
    ViewBag.Title = "İçerik Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section CssFiles {
    <link rel="stylesheet" href="~/FrontendFiles/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

}



<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Yeni İçerik Yazısı Girişi</h1>
            </div>

        </div>
    </div>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">


            <div class="col-md-9">

                @using (Html.BeginForm("AddContent", "Content", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {

                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Yeni İçerik Yazısı Oluştur</h3>
                        </div>

                        <div class="card-body">
                            <div class="form-group">

                                @Html.Label("İçerik başlığı giriniz:")
                                @Html.TextBoxFor(x => x.ContentTitle, new { PlaceHolder = "Lütfen başlık giriniz...", @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.ContentTitle, "", new { @style = "color:red" })

                            </div>
                            <div class="form-group">
                                @Html.Label("İçerik giriniz:")
                                <textarea id="compose-textarea" name="ContentValue" class="form-control" style="height: 300px"></textarea>
                            </div>
                            <div class="form-group">

                                @Html.Label("Aktiflik durumu giriniz:")
                                @Html.DropDownListFor(x => x.ContentStatus, (List<SelectListItem>)ViewBag.StatusType, new { @class = "form-control" })

                            </div>
                            <div class="form-group">

                                @Html.Label("İçerik yazarı seçiniz:")
                                @Html.DropDownListFor(x => x.WriterId, (List<SelectListItem>)ViewBag.valueWriter, new { @class = "form-control" })

                            </div>

                            <div class="form-group">
                                @Html.Label("İçerik kategorisi girin:")
                                @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.valueCategory, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                @Html.Label("İçerik görseli yükleyiniz:")
                                <br />
                                <input type="file" name="ContentImage" />
                                <p class="help-block">Max. 32MB</p>
                            </div>
                        </div>

                        <div class="card-footer">
                            <div class="float-right">

                                <button type="submit" class="btn btn-primary"><i class="far fa-envelope"></i> Kaydet</button>
                            </div>
                            <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> İptal Et</button>
                        </div>

                    </div>

                }


            </div>

        </div>

    </div>
</section>


@section Scripts {
    <script src="~/FrontendFiles/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>

}


<script src="~/FrontendFiles/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
<script src="~/FrontendFiles/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
<script src="~/FrontendFiles/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>



<script>
    $(function () {
        //Add text editor
        $('#compose-textarea').summernote()
    })</script>

HealthBlog/Views/Content/AdminContents.cshtml
@using HealthBlog.Entities.Concrete
@*@using PagedList;
    @using PagedList.Mvc;*@

@model List<Content>


@{
    ViewBag.Title = "İçerik Listesi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />


@{ string color = ""; }



<body class="hold-transition sidebar-mini">

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
            </div>
        </div>
    </section>

    <section class="content">

        <div class="card" style="background-color:aquamarine;">
            <div class="card-header">


            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 15%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 10%">
                                Durum
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {

                            if (item.CategoryId == 1)
                            {
                                color = "badge badge-warning";
                            }

                            if (item.CategoryId == 2)
                            {
                                color = "badge badge-success";
                            }

                            if (item.CategoryId == 3)
                            {
                                color = "badge badge-info";
                            }

                            if (item.CategoryId == 4)
                            {
                                color = "badge badge-secondary";
                            }


                            <tr>
                                <td>
                                    @item.ContentId
                                </td>
                                <td>
                                    <a>
                                        @item.ContentTitle
                                    </a>
                                    <br />
                                    <small>
                                        @item.ContentDate
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="~/FrontendFiles/WriterImages/@item.Writer.WriterImage">
                                            @item.Writer.WriterTitle @item.Writer.WriterName @item.Writer.WriterSurname
                                        </li>
                                    </ul>
                                </td>
                                <td>

                                    @if (item.ContentStatus == true)
                                    {
                                        <span class="badge badge-success">@item.ContentStatus</span>
                                    }


                                    @if (item.ContentStatus == false)
                                    {
                                        <span class="badge badge-warning">@item.ContentStatus</span>
                                    }
                                </td>
                                <td class="project-state">
                                    <span class="@color">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.ContentId">
                                        <i class="fas fa-folder">
                                        </i>
                                        Yazılar
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/Content/EditContent/@item.ContentId">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/Content/DeleteContent/@item.ContentId">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>


                @*<div class="block-27">
                        @Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index","Content", new { sayfa }))
                    </div>*@


            </div>

        </div>

    </section>
</body>


<a href="/Content/AddContent/" class="btn btn-primary">Yeni İçerik Ekle</a>

HealthBlog/Views/Content/ContentReport.cshtml
@using HealthBlog.Entities.Concrete
@model List<Content>


@{
    ViewBag.Title = "Rapor";
    Layout = null;
}

<br />
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Raporlama</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
</head>
<body>


    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
        <thead>
            <tr>
                <th>Başlık Id</th>
                <th>Başlık Adı</th>
                <th>Tarih</th>
                <th>Yazar</th>
                <th>Kategori</th>
                <th>Durum</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var x in Model)
            {
                <tr>
                    <td>@x.ContentId</td>
                    <td>@x.ContentTitle</td>
                    <td>@x.ContentDate</td>
                    <td>@x.Writer.WriterTitle @x.Writer.WriterName @x.Writer.WriterSurname</td>
                    <td>@x.Category.CategoryName</td>
                    <td>@x.ContentStatus</td>
                </tr>
            }

        </tbody>
    </table>






    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            var table = $('#example').DataTable({
                lengthChange: false,
                buttons: ['copy', 'excel', 'csv', 'pdf', 'colvis']
            });

            table.buttons().container()
                .appendTo('#example_wrapper .col-md-6:eq(0)');
        });
    </script>
</body>
</html>

HealthBlog/Views/Content/EditContent.cshtml
@model HealthBlog.Entities.Concrete.Content

@{
    ViewBag.Title = "İçerik Düzenle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section CssFiles {
    <link rel="stylesheet" href="~/FrontendFiles/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

}



<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Yeni İçerik Yazısı Girişi</h1>
            </div>

        </div>
    </div>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">


            <div class="col-md-9">

                @using (Html.BeginForm("EditContent", "Content", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {

                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Yeni İçerik Yazısı Oluştur</h3>
                        </div>

                        <div class="card-body">

                            <div class="form-group">

                                @Html.Label("İçerik id:")
                                @Html.TextBoxFor(x => x.ContentId, new { PlaceHolder = "Lütfen başlık giriniz...", @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.ContentId, "", new { @style = "color:red" })

                            </div>

                            <div class="form-group">

                                @Html.Label("İçerik başlığı giriniz:")
                                @Html.TextBoxFor(x => x.ContentTitle, new { PlaceHolder = "Lütfen başlık giriniz...", @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.ContentTitle, "", new { @style = "color:red" })

                            </div>
                            <div class="form-group">
                                @Html.Label("İçerik giriniz:")
                                <textarea id="compose-textarea" name="ContentValue" class="form-control" style="height: 300px"></textarea>
                            </div>
                            <div class="form-group">

                                @Html.Label("Aktiflik durumu giriniz:")
                                @Html.DropDownListFor(x => x.ContentStatus, (List<SelectListItem>)ViewBag.StatusType, new { @class = "form-control" })

                            </div>
                            <div class="form-group">
                                @Html.Label("İçerik Tarihi:")
                                @Html.TextBoxFor(x => x.ContentDate, new { type = "date", @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.ContentDate, "", new { @style = "color:red" })


                            </div>
                            <div class="form-group">

                                @Html.Label("İçerik yazarı seçiniz:")
                                @Html.DropDownListFor(x => x.WriterId, (List<SelectListItem>)ViewBag.valueWriter, new { @class = "form-control" })

                            </div>

                            <div class="form-group">
                                @Html.Label("İçerik kategorisi girin:")
                                @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.valueCategory, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                @Html.Label("İçerik görseli yükleyiniz:")
                                <br />
                                <input type="file" name="ContentImage" />
                                <p class="help-block">Max. 32MB</p>
                            </div>
                        </div>

                        <div class="card-footer">
                            <div class="float-right">

                                <button type="submit" class="btn btn-primary"><i class="far fa-envelope"></i> Kaydet</button>
                            </div>
                            <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> İptal Et</button>
                        </div>

                    </div>

                }


            </div>

        </div>

    </div>
</section>


@section Scripts {
    <script src="~/FrontendFiles/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>

}


<script src="~/FrontendFiles/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
<script src="~/FrontendFiles/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
<script src="~/FrontendFiles/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>



<script>
    $(function () {
        //Add text editor
        $('#compose-textarea').summernote()
    })</script>

HealthBlog/Views/Content/Index.cshtml
@using HealthBlog.Entities.Concrete
@*@using PagedList;
@using PagedList.Mvc;*@

@model List<Content>


@{
    ViewBag.Title = "İçerik Listesi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />


@{ string color = ""; }



<body class="hold-transition sidebar-mini">

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
            </div>
        </div>
    </section>

    <section class="content">

        <div class="card" style="background-color:aquamarine;">
            <div class="card-header">
                

            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 15%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 10%">
                                Durum
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {

                            if (item.CategoryId == 1)
                            {
                                color = "badge badge-warning";
                            }

                            if (item.CategoryId == 2)
                            {
                                color = "badge badge-success";
                            }

                            if (item.CategoryId == 3)
                            {
                                color = "badge badge-info";
                            }

                            if (item.CategoryId == 4)
                            {
                                color = "badge badge-secondary";
                            }


                            <tr>
                                <td>
                                    @item.ContentId
                                </td>
                                <td>
                                    <a>
                                        @item.ContentTitle
                                    </a>
                                    <br />
                                    <small>
                                        @item.ContentDate
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="~/FrontendFiles/WriterImages/@item.Writer.WriterImage">
                                            @item.Writer.WriterTitle @item.Writer.WriterName @item.Writer.WriterSurname
                                        </li>
                                    </ul>
                                </td>
                                <td>

                                    @if (item.ContentStatus == true)
                                    {
                                        <span class="badge badge-success">@item.ContentStatus</span>
                                    }


                                    @if (item.ContentStatus == false)
                                    {
                                        <span class="badge badge-warning">@item.ContentStatus</span>
                                    }
                                </td>
                                <td class="project-state">
                                    <span class="@color">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.ContentId">
                                        <i class="fas fa-folder">
                                        </i>
                                        Yazılar
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/Content/EditContent/@item.ContentId">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/Content/DeleteContent/@item.ContentId">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>


                        @*<div class="block-27">
                            @Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index","Content", new { sayfa }))
                        </div>*@


            </div>

        </div>

    </section>
</body>


<a href="/Content/AddContent/" class="btn btn-primary">Yeni İçerik Ekle</a>