HealthBlog/Controllers/GalleryController.cs
using HealthBlog.Bussiness.Concrete;
using HealthBlog.DataAccess.Concrete.EntityFramework;
using HealthBlog.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HealthBlog.Controllers
{
    public class GalleryController : Controller
    {
        ImageFileManager imageFile = new ImageFileManager(new EfImageFileDal());
        ContentManager contentManager = new ContentManager(new EfContentDal());

        public ActionResult Images()
        {
            var list = imageFile.GetImageFileList();
            return View(list);
        }

        [HttpGet]
        public ActionResult AddImages()
        {
            List<SelectListItem> valueContent = (from x in contentManager.GetContentList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.ContentTitle,
                                                      Value = x.ContentId.ToString()
                                                  }).ToList();

            ViewBag.valueContent = valueContent;



            return View();
        }

        [HttpPost]
        public ActionResult AddImages(ImageFile ımageFile)
        {

            if (Request.Files.Count > 0)
            {
                string filename = Path.GetFileName(Request.Files[0].FileName);
                string _filename = DateTime.Now.ToString("yymmssfff") + filename;
                string path = "~/FrontendFiles/Gallery/" + _filename;
                Request.Files[0].SaveAs(Server.MapPath(path));
                ımageFile.ImagePath = _filename;
            }



            imageFile.AddImageFile(ımageFile);
            return RedirectToAction("AdminImages");
        }


        [HttpGet]
        public ActionResult UpdateImage(int id)
        {
            var value = imageFile.GetImageFile(id);

            List<SelectListItem> valueContent = (from x in contentManager.GetContentList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.ContentTitle,
                                                     Value = x.ContentId.ToString()
                                                 }).ToList();

            ViewBag.valueContent = valueContent;

            return View(value);
        }

        [HttpPost]
        public ActionResult UpdateImage(ImageFile c)
        {

            if (Request.Files.Count > 0)
            {
                string filename = Path.GetFileName(Request.Files[0].FileName);
                string _filename = DateTime.Now.ToString("yymmssfff") + filename;
                string path = "~/FrontendFiles/Gallery/" + _filename;
                Request.Files[0].SaveAs(Server.MapPath(path));
                c.ImagePath = _filename;
            }

            imageFile.UpdateImageFile(c);
            return RedirectToAction("AdminImages");
        }


        public ActionResult AdminImages()
        {
            var imageFiles = imageFile.GetImageFileList();
            return View(imageFiles);
        }


        public ActionResult DeleteImageFile(int id)
        {
            var entity = imageFile.GetImageFile(id);
            imageFile.DeleteImageFile(entity);
            return RedirectToAction("AdminImages");
        }

        public ActionResult DenemeSil()
        {
            var list = imageFile.GetImageFileList();
            return View(list);
        }

        public ActionResult DenemeSil2()
        {
           
            return View();
        }

        public ActionResult GaleriGuzel()
        {

            return View();
        }

        public ActionResult GalerySlider()
        {

            return View();
        }

        public PartialViewResult Slider(int id)
        {
            var  list = imageFile.ImageFileListByContent(id);
            return PartialView(list);
        }

    }
}

HealthBlog/Views/Gallery/AddImages.cshtml
@model HealthBlog.Entities.Concrete.ImageFile

@{
    ViewBag.Title = "Resim Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Add Images</h2>


@using (Html.BeginForm("AddImages", "Gallery", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">

        @Html.Label("Resim başlığı:")
        @Html.TextBoxFor(x => x.ImageName, new { PlaceHolder = "Başlık girin...", @class = "form-control" })
        <br />
        @Html.Label("Resim açıklaması:")
        @Html.TextBoxFor(x => x.ImageDescription, new { PlaceHolder = "Açıklama girin...", @class = "form-control" })
        <br />
        @Html.Label("Hangi içeriğe resim ekleyeceğinizi seçiniz:")
        @Html.DropDownListFor(x => x.ContentId, (List<SelectListItem>)ViewBag.valueContent, new { @class = "form-control" })

        <br />
        <input type="file" name="ImagePath" />
        <br /><br />
        <button class="btn btn-info">Kaydet</button>

    </div>
}

HealthBlog/Views/Gallery/AdminImages.cshtml
@using HealthBlog.Entities.Concrete
@model List<ImageFile>

@{
    ViewBag.Title = "Görseller";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@section CssFiles {

    <link rel="stylesheet" href="~/FrontendFiles/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/FrontendFiles/AdminLTE-3.0.4/plugins/ekko-lightbox/ekko-lightbox.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="~/FrontendFiles/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

}





<body class="hold-transition sidebar-mini">


    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 style="color:darkred;font-weight:bold;">Galeri</h1>
                </div>

            </div>
        </div>
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <div class="card-title">
                                Görsellerimiz
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="row">

                                @foreach (var item in Model)
                                {

                                    <br />

                                    <div class="col-sm-2">
                                        <a href="~/FrontendFiles/Gallery/@item.ImagePath" data-toggle="lightbox" data-title="@item.ImageName" data-gallery="gallery">
                                            <img src="~/FrontendFiles/Gallery/@item.ImagePath" class="img-fluid mb-2" alt="white sample" style="width:187px;height:113px;" />
                                        </a>
                                        <a href="/Gallery/DeleteImageFile/@item.ImageId" class="btn btn-danger">SİL</a>
                                        <a href="/Gallery/UpdateImage/@item.ImageId" class="btn btn-success">GÜNCELLE</a>

                                    </div>
                                    <br />
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <a href="/Gallery/AddImages/" class="btn btn-outline-success">RESİM EKLE</a>

    </section>

    @section Scripts {

        <script src="~/FrontendFiles/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
        <script src="~/FrontendFiles/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="~/FrontendFiles/AdminLTE-3.0.4/plugins/jquery-ui/jquery-ui.min.js"></script>
        <script src="~/FrontendFiles/AdminLTE-3.0.4/plugins/ekko-lightbox/ekko-lightbox.min.js"></script>
        <script src="~/FrontendFiles/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
        <script src="~/FrontendFiles/AdminLTE-3.0.4/dist/js/demo.js"></script>
        <script src="~/FrontendFiles/AdminLTE-3.0.4/plugins/filterizr/jquery.filterizr.min.js"></script>

        <script>
            $(function () {
                $(document).on('click', '[data-toggle="lightbox"]', function (event) {
                    event.preventDefault();
                    $(this).ekkoLightbox({
                        alwaysShowClose: true
                    });
                });

                $('.filter-container').filterizr({ gutterPixels: 3 });
                $('.btn[data-filter]').on('click', function () {
                    $('.btn[data-filter]').removeClass('active');
                    $(this).addClass('active');
                });
            })</script>


    }


</body>

HealthBlog/Views/Gallery/GaleriGuzel.cshtml
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->





<style>

    @media (min-width: 768px) {

    /* show 3 items */
    .carouselPrograms .carousel-inner .active,
    .carouselPrograms .carousel-inner .active + .carousel-item,
    .carouselPrograms .carousel-inner .active + .carousel-item + .carousel-item {
        display: block;
    }

    .carouselPrograms .carousel-inner .carousel-item.active:not(.carousel-item-right):not(.carousel-item-left),
    .carouselPrograms .carousel-inner .carousel-item.active:not(.carousel-item-right):not(.carousel-item-left) + .carousel-item,
    .carouselPrograms .carousel-inner .carousel-item.active:not(.carousel-item-right):not(.carousel-item-left) + .carousel-item + .carousel-item {
        transition: none;
    }

    .carouselPrograms .carousel-inner .carousel-item-next,
    .carouselPrograms .carousel-inner .carousel-item-prev {
        position: relative;
        transform: translate3d(0, 0, 0);
    }

    .carouselPrograms .carousel-inner .active.carousel-item + .carousel-item + .carousel-item + .carousel-item {
        position: absolute;
        top: 0;
        right: -33.333%;
        z-index: -1;
        display: block;
        visibility: visible;
    }

    /* left or forward direction */
    .carouselPrograms .active.carousel-item-left + .carousel-item-next.carousel-item-left,
    .carouselPrograms .carousel-item-next.carousel-item-left + .carousel-item,
    .carouselPrograms .carousel-item-next.carousel-item-left + .carousel-item + .carousel-item,
    .carouselPrograms .carousel-item-next.carousel-item-left + .carousel-item + .carousel-item + .carousel-item {
        position: relative;
        transform: translate3d(-100%, 0, 0);
        visibility: visible;
    }

    /* farthest right hidden item must be abso position for animations */
    .carouselPrograms .carousel-inner .carousel-item-prev.carousel-item-right {
        position: absolute;
        top: 0;
        left: 0%;
        z-index: -1;
        display: block;
        visibility: visible;
    }

    /* right or prev direction */
    .carouselPrograms .active.carousel-item-right + .carousel-item-prev.carousel-item-right,
    .carouselPrograms .carousel-item-prev.carousel-item-right + .carousel-item,
    .carouselPrograms .carousel-item-prev.carousel-item-right + .carousel-item + .carousel-item,
    .carouselPrograms .carousel-item-prev.carousel-item-right + .carousel-item + .carousel-item + .carousel-item {
        position: relative;
        transform: translate3d(100%, 0, 0);
        visibility: visible;
        display: block;
        visibility: visible;
    }
}



</style>



<div class="container-fluid">
    <div id="carouselExample" class="carouselPrograms carousel slide" data-ride="carousel" data-interval="false">
        <div class="carousel-inner row w-100 mx-auto" role="listbox">
            <div class="carousel-item col-md-4  active">
                <div class="panel panel-default">
                    <div class="panel-thumbnail">
                        <a href="#" title="image 1" class="thumb">
                            <img class="img-fluid mx-auto d-block" src="//via.placeholder.com/600x400?text=1" alt="slide 1">
                        </a>
                    </div>
                </div>
            </div>
            <div class="carousel-item col-md-4 ">
                <div class="panel panel-default">
                    <div class="panel-thumbnail">
                        <a href="#" title="image 3" class="thumb">
                            <img class="img-fluid mx-auto d-block" src="//via.placeholder.com/600x400?text=2" alt="slide 2">
                        </a>
                    </div>
                </div>
            </div>
            <div class="carousel-item col-md-4 ">
                <div class="panel panel-default">
                    <div class="panel-thumbnail">
                        <a href="#" title="image 4" class="thumb">
                            <img class="img-fluid mx-auto d-block" src="//via.placeholder.com/600x400?text=3" alt="slide 3">
                        </a>
                    </div>
                </div>
            </div>
            <div class="carousel-item col-md-4 ">
                <div class="panel panel-default">
                    <div class="panel-thumbnail">
                        <a href="#" title="image 5" class="thumb">
                            <img class="img-fluid mx-auto d-block" src="//via.placeholder.com/600x400?text=4" alt="slide 4">
                        </a>
                    </div>
                </div>
            </div>
            <div class="carousel-item col-md-4 ">
                <div class="panel panel-default">
                    <div class="panel-thumbnail">
                        <a href="#" title="image 6" class="thumb">
                            <img class="img-fluid mx-auto d-block" src="//via.placeholder.com/600x400?text=5" alt="slide 5">
                        </a>
                    </div>
                </div>
            </div>
            <div class="carousel-item col-md-4 ">
                <div class="panel panel-default">
                    <div class="panel-thumbnail">
                        <a href="#" title="image 7" class="thumb">
                            <img class="img-fluid mx-auto d-block" src="//via.placeholder.com/600x400?text=6" alt="slide 6">
                        </a>
                    </div>
                </div>
            </div>
            <div class="carousel-item col-md-4 ">
                <div class="panel panel-default">
                    <div class="panel-thumbnail">
                        <a href="#" title="image 8" class="thumb">
                            <img class="img-fluid mx-auto d-block" src="//via.placeholder.com/600x400?text=7" alt="slide 7">
                        </a>
                    </div>
                </div>
            </div>
            <div class="carousel-item col-md-4  ">
                <div class="panel panel-default">
                    <div class="panel-thumbnail">
                        <a href="#" title="image 2" class="thumb">
                            <img class="img-fluid mx-auto d-block" src="//via.placeholder.com/600x400?text=8" alt="slide 8">
                        </a>
                    </div>

                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next text-faded" href="#carouselExample" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

HealthBlog/Views/Gallery/Images.cshtml
@using HealthBlog.Entities.Concrete
@model List<ImageFile>

@{
    ViewBag.Title = "DenemeSil";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@section CssFiles {


    <link rel="shortcut icon" type="image/x-icon" href="~/FrontendFiles/BlogContent/assets/img/favicon.ico">
    <link rel="stylesheet" href="~/FrontendFiles/BlogContent/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/FrontendFiles/BlogContent/assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/FrontendFiles/BlogContent/assets/css/slicknav.css">
    <link rel="stylesheet" href="~/FrontendFiles/BlogContent/assets/css/animate.min.css">
    <link rel="stylesheet" href="~/FrontendFiles/BlogContent/assets/css/hamburgers.min.css">
    <link rel="stylesheet" href="~/FrontendFiles/BlogContent/assets/css/magnific-popup.css">
    <link rel="stylesheet" href="~/FrontendFiles/BlogContent/assets/css/themify-icons.css">
    <link rel="stylesheet" href="~/FrontendFiles/BlogContent/assets/css/slick.css">
    <link rel="stylesheet" href="~/FrontendFiles/BlogContent/assets/css/nice-select.css">
    <link rel="stylesheet" href="~/FrontendFiles/BlogContent/assets/css/style.css">

}

<div class="section-top-border">
    <h3 style="font-family: Papyrus," Sagoe UI",monospace;">Bizden Kareler...</h3>
    <div class="row gallery-item">

        @foreach (var x in Model)
        {



            <div class="col-md-4">
                @*<a href="~/FrontendFiles/BlogContent/assets/img/elements/g1.jpg" class="img-pop-up">*@
                <a href="~/FrontendFiles/Gallery/@x.ImagePath" class="img-pop-up">
                    <div class="single-gallery-image" style="background: url(../../FrontendFiles/Gallery/@x.ImagePath);"></div>
                </a>
            </div>


        }


    </div>
</div>


@section Scripts {

    <script src="~/FrontendFiles/BlogContent/assets/js/vendor/modernizr-3.5.0.min.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/popper.min.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/bootstrap.min.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/jquery.slicknav.min.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/owl.carousel.min.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/slick.min.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/wow.min.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/animated.headline.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/jquery.magnific-popup.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/gijgo.min.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/jquery.nice-select.min.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/jquery.sticky.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/jquery.counterup.min.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/waypoints.min.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/jquery.countdown.min.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/hover-direction-snake.min.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/contact.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/jquery.form.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/jquery.validate.min.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/mail-script.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/plugins.js"></script>
    <script src="~/FrontendFiles/BlogContent/assets/js/main.js"></script>

}

HealthBlog/Views/Gallery/UpdateImage.cshtml
@model HealthBlog.Entities.Concrete.ImageFile


@{
    ViewBag.Title = "Düzenle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h2>GÜNCELLE</h2>
<br />

@using (Html.BeginForm("UpdateImage", "Gallery", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="form-group">

    @Html.Label("Resim ID:")
    @Html.TextBoxFor(x => x.ImageId, new { @class = "form-control" })
    <br />
    @Html.Label("Resim başlığı:")
    @Html.TextBoxFor(x => x.ImageName, new { PlaceHolder = "Başlık girin...", @class = "form-control" })
    <br />
    @Html.Label("Resim açıklaması:")
    @Html.TextBoxFor(x => x.ImageDescription, new { PlaceHolder = "Açıklama girin...", @class = "form-control" })
    <br />
    @Html.Label("Hangi içeriğe resim ekleyeceğinizi seçiniz:")
    @Html.DropDownListFor(x => x.ContentId, (List<SelectListItem>)ViewBag.valueContent, new { @class = "form-control" })

    <br />
    <input type="file" name="ImagePath" />
    <br /><br />
    <button class="btn btn-info">Kaydet</button>


</div>

}