HealthBlog/Controllers/BlogController.cs
using HealthBlog.Bussiness.Concrete;
using HealthBlog.DataAccess.Concrete.EntityFramework;
using HealthBlog.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HealthBlog.Controllers
{
    public class BlogController : Controller
    {
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());
        ContentManager contentManager = new ContentManager(new EfContentDal());
        CommentManager commentManager = new CommentManager(new EfCommentDal());


        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult CategoryList()
        {
            IEnumerable<Category> list = categoryManager.GetCategoryList().Take(8);
            int[] dizi = new int[8];
            int k = 0;


            foreach (var item in list)
            {

                dizi[k] = contentManager.NumberOfContentByCategory(item.CategoryId);
                k++;

            }

            ViewBag.counter = dizi;
            return PartialView(list);
        }


        public PartialViewResult RecentlyPost()
        {
            IEnumerable<Content> list = contentManager.GetContentList().OrderByDescending(x => x.ContentDate).Take(5);
            return PartialView(list);
        }


        public ActionResult BlogSingle(int id)
        {
            var content = contentManager.GetByID(id);
            return View(content);
        }

        public PartialViewResult Comments(int id)
        {
            //IEnumerable<Content> list = contentManager.GetContentList().OrderByDescending(x => x.ContentDate).Take(5);
            List<Comment> list = commentManager.CommentsByContent(id);
            ViewBag.total = list.Count();
            return PartialView(list);
        }



    }
}

HealthBlog/Controllers/CategoriesPageController.cs
using HealthBlog.Bussiness.Concrete;
using HealthBlog.DataAccess.Concrete.EntityFramework;
using HealthBlog.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace HealthBlog.Controllers
{
    public class CategoriesPageController : Controller
    {

        //CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());
        ContentManager contentManager = new ContentManager(new EfContentDal());


        public ActionResult Index()
        {
            var list = contentManager.GetContentList();

            IEnumerable<IGrouping<string, Content>> groups = list.GroupBy(x => x.Category.CategoryName);

            ViewBag.counter = list.Count();
            ViewBag.list = list;

            return View(groups);
        }

        public ActionResult CategoryDetail(int id,int sayfa=1)
        {
             var list = contentManager.ContentListByCategoryId(id).ToPagedList(sayfa, 2);
             var title = contentManager.ContentByCategoryId(id);
             ViewBag.categoryname = title.Category.CategoryName; 

            return View(list);
        }

        public PartialViewResult RecentlyPost()
        {
            IEnumerable<Content> list = contentManager.GetContentList().OrderByDescending(x => x.ContentDate).Take(5);
            return PartialView(list);
        }

        public PartialViewResult TwelveContents()
        {
            IEnumerable<Content> list = contentManager.GetContentList().OrderByDescending(x => x.ContentDate).Take(12);
            return PartialView(list);
        }

        public PartialViewResult ReadMore()
        {
            IEnumerable<Content> list = contentManager.GetContentList().OrderBy(x => x.ContentDate).Take(12);
            return PartialView(list);
        }

    }
}

HealthBlog/Views/CategoriesPage/CategoryDetail.cshtml
@using HealthBlog.Entities.Concrete
@using PagedList;
@using PagedList.Mvc;

@model PagedList.IPagedList<Content>


@{
    ViewBag.Title = "Kategori";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}




<!-- END nav -->
<section class="hero-wrap hero-wrap-2" style=" background-image: url(~/FrontendFiles/main/images/bg_2.jpg);" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end">
            <div class="col-md-9 ftco-animate pb-5">
                <p class="breadcrumbs mb-2"><span class="mr-2"><a href="/CategoriesPage/Index/">KATEGORİLER<i class="ion-ios-arrow-forward"></i></a></span> <span><i class="ion-ios-arrow-forward"></i></span></p>
                <h1 style="font-weight:800;font-size:100px;" class="mb-0 bread">@ViewBag.categoryname</h1>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 ftco-animate">

                <!--for dön-->
                @foreach (var x in Model)
                {



                    <div class="cases-wrap d-md-flex align-items-center">
                        <div class="img" style=" background-image: url(/FrontendFiles/ContentImages/@x.ContentImage);"></div>
                        <div class="text pl-md-5">
                            <span class="cat">@x.Writer.WriterTitle @x.Writer.WriterName @x.Writer.WriterSurname</span>
                            <h2>@x.ContentTitle</h2>
                            <p>@x.ContentValue.Substring(0,120) ...</p>
                            <p><a href="/Blog/BlogSingle/@x.ContentId" class="btn btn-primary">DEVAMINI OKU</a></p>
                        </div>
                    </div>

                }




                <div class="row mt-5">
                    <div class="col">
                        <div class="block-27">
                            @Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("CategoryDetail", new { sayfa }))
                        </div>
                    </div>
                </div>

            </div> <!-- .col-md-8 -->
            <div class="col-lg-4 sidebar pl-lg-5 ftco-animate">
                <div class="sidebar-box">
                    <form action="#" class="search-form">
                        <div class="form-group">
                            <span class="fa fa-search"></span>
                            <input type="text" class="form-control" placeholder="ARA">
                        </div>
                    </form>
                </div>

                @Html.Action("CategoryList", "Blog")


                @Html.Action("RecentlyPost", "CategoriesPage")


                <div class="sidebar-box ftco-animate">
                    <h3>Tag Cloud</h3>
                    <div class="tagcloud">
                        <a href="#" class="tag-cloud-link">home</a>
                        <a href="#" class="tag-cloud-link">builder</a>
                        <a href="#" class="tag-cloud-link">build</a>
                        <a href="#" class="tag-cloud-link">create</a>
                        <a href="#" class="tag-cloud-link">make</a>
                        <a href="#" class="tag-cloud-link">construction</a>
                        <a href="#" class="tag-cloud-link">house</a>
                        <a href="#" class="tag-cloud-link">architect</a>
                    </div>
                </div>

            </div>

        </div>
    </div>
</section> <!-- .section -->

HealthBlog/Views/CategoriesPage/Index.cshtml
@using HealthBlog.Entities.Concrete
@model IEnumerable<IGrouping<string, Content>>

@{
    ViewBag.Title = "Kategoriler";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}



@section CssFiles {

    <link href="~/FrontendFiles/Category/img/favicon.ico" rel="icon">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="~/FrontendFiles/Category/lib/slick/slick.css" rel="stylesheet">
    <link href="~/FrontendFiles/Category/lib/slick/slick-theme.css" rel="stylesheet">
    <link href="~/FrontendFiles/Category/css/style.css" rel="stylesheet">


}


@{var list = ViewBag.list;}
@{int categoryId = 2;}




<div class="cat-news">
    <div class="container">
        <div class="row">
            <!-- 1 satırda 2 tane var demek-->
            <!--1.for buraya gelir-->
            @foreach (var x in Model)
            {


                <div class="col-md-6">
                    <h2><a href="#">@x.Key</a></h2>
                    <div class="row cn-slider">

                        <!--3 tane olacak for dön-->
                        @foreach (var y in x)
                        {


                            <div class="col-md-6">
                                <div class="cn-img">
                                    <img src="~/FrontendFiles/ContentImages/@y.ContentImage" style="width:255px;height:171px;"/>
                                    <div class="cn-title">
                                        <a href="/Blog/BlogSingle/@y.ContentId">@y.ContentTitle</a>
                                    </div>
                                </div>
                            </div>
                            <!--3 tane olacak-->
                            categoryId = y.Category.CategoryId;
                        }
                    </div>
                    <a href="/CategoriesPage/CategoryDetail/@categoryId" class="btn btn-success" style="margin-left:85%;">TÜMÜ</a>
                </div>
            }

        </div>
    </div>
</div>


@Html.Action("TwelveContents","CategoriesPage")

<a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

@section Scripts {

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="~/FrontendFiles/Category/lib/easing/easing.min.js"></script>
    <script src="~/FrontendFiles/Category/lib/slick/slick.min.js"></script>
    <script src="~/FrontendFiles/Category/js/main.js"></script>

}

HealthBlog/Views/CategoriesPage/ReadMore.cshtml
@using HealthBlog.Entities.Concrete
@model IEnumerable<Content>


<div class="col-lg-3">
    <div class="mn-list">
        <h2>Daha Fazla Oku</h2>
        <ul>

            @foreach (var x in Model)
            {

                <li><a href="/Blog/BlogSingle/@x.ContentId">@x.ContentTitle</a></li>

            }

        </ul>
    </div>
</div>

HealthBlog/Views/CategoriesPage/RecentlyPost.cshtml
@using HealthBlog.Entities.Concrete
@model IEnumerable<Content>




<div class="sidebar-box ftco-animate">
    <h3 style="color:brown;font-weight:bold;">Son Yazılar</h3>

    @foreach (var x in Model)
    {

        <div class="block-21 mb-4 d-flex">
            <a class="blog-img mr-4" style="background-image: url(/FrontendFiles/ContentImages/@x.ContentImage);"></a>
            <div class="text">
                <h3 class="heading" style="color:greenyellow;font-weight:bold;"><a href="/Blog/BlogSingle/@x.ContentId">@x.ContentTitle</a></h3>
                <div class="meta">
                    <div><span class="icon-calendar" style="color:green;">@x.ContentDate.ToString()</span></div>
                    <div style="color:dodgerblue;font-weight:bold;"><a href="/Writer/WriterDetail/@x.Writer.WriterId"><span class="icon-person">@x.Writer.WriterTitle @x.Writer.WriterName @x.Writer.WriterSurname</span></a></div>
                    <div><a href="/CategoriesPage/CategoryDetail/@x.CategoryId" style="color:crimson"><span class="icon-chat"></span>@x.Category.CategoryName</a></div>
                </div>
                <hr />
            </div>
        </div>

    }
</div>

HealthBlog/Views/CategoriesPage/TwelveContents.cshtml
@using HealthBlog.Entities.Concrete
@model IEnumerable<Content>



<div class="main-news">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="row">

                    @foreach (var x in Model)
                    {



                        <div class="col-md-4">
                            <div class="mn-img">
                                <img src="~/FrontendFiles/ContentImages/@x.ContentImage" style="width:255px;height:162px;"/>
                                <div class="mn-title">
                                    <a href="/Blog/BlogSingle/@x.ContentId">@x.ContentTitle</a>
                                </div>
                            </div>
                        </div>



                    }

                </div>
            </div>

            @Html.Action("ReadMore", "CategoriesPage")



        </div>
    </div>
</div>